application: gridlock-exchange
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /(apple-touch-icon.*)
  static_files: static/\1
  upload: static/apple-touch-icon.*

- url: /(crossdomain.xml|robots.txt|humans.txt)
  static_files: static/\1
  upload: static/(crossdomain.xml|robots.txt|humans.txt)

- url: /static
  static_dir: static

- url: .*
  script: exchange.app

libraries:
- name: jinja2
  version: "2.6"

- name: markupsafe
  version: "0.15"

- name: pycrypto
  version: "2.6"
